apiVersion: v1
kind: ServiceAccount
metadata:
  name: jwt-demo
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: jwt-demo
  namespace: default
  labels:
    app: jwt-demo
    spiffe.io/spire-managed-identity: "true"
spec:
  serviceAccountName: jwt-demo
  initContainers:
    - name: fetch-jwt
      image: ghcr.io/spiffe/spire-agent:1.15.3
      command:
        - /opt/spire/bin/spire-agent
      args:
        - api
        - fetch
        - jwt
        - -socketPath
        - /spiffe-workload-api/spire-agent.sock
        - -audience
        - jwt-demo
      volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true
  containers:
    - name: sleep
      image: alpine:3.22
      command:
        - /bin/sh
        - -c
        - sleep infinity
  volumes:
    - name: spiffe-workload-api
      csi:
        driver: "csi.spiffe.io"
        readOnly: true